export const PHONE_1 = "9310651066";
export const PHONE_2 = "9315879315";
export const EMAIL = "xpertawards23@gmail.com";
export const WHATSAPP_URL = `https://wa.me/91${PHONE_1}?text=Hi%20Xpert%20Awards%2C%20I%20am%20interested%20in%20your%20products.`;
export const ADDRESS = "Shop No. - 2/73, GF, Lalita Park, Near Gurudwara, Laxmi Nagar, New Delhi, 110092";

export const CATEGORIES = [
  {
    slug: "wooden-trophy",
    title: "Wooden Trophy",
    description: "Personalized trophies designed to celebrate unique achievements with premium materials and craftsmanship.",
    material: "Premium Wood with Metal/Gold Plating",
  },
  {
    slug: "acrylic-trophy",
    title: "Acrylic Trophy",
    description: "Corporate and academic recognition pieces that honor excellence and motivate continued success.",
    material: "High-grade Acrylic Crystal",
  },
  {
    slug: "fiber-trophy",
    title: "Fiber Trophy",
    description: "Grand championship trophies and awards for sporting events, competitions, and tournaments.",
    material: "Durable Fiber with Gold/Silver Finish",
  },
  {
    slug: "metal-trophy",
    title: "Metal Trophy",
    description: "High-quality metal trophies designed to showcase remarkable achievements with lasting elegance.",
    material: "Brass / Stainless Steel / Zinc Alloy",
  },
  {
    slug: "sports-medals",
    title: "Sports Medals",
    description: "Elegant and customizable medals perfect for corporate events, clients, and employee recognition.",
    material: "Metal with Custom Ribbon",
  },
  {
    slug: "corporate-gifts",
    title: "Corporate Gifts",
    description: "Complete award solutions for schools, colleges, and large-scale events with custom branding.",
    material: "Mixed Premium Materials",
  },
] as const;

export interface ProductItem {
  id: string;
  name: string;
  image: string;
  size: string;
}

export const PRODUCT_ITEMS: Record<string, ProductItem[]> = {
  "wooden-trophy": [
    { id: "TRO-W1", name: "TRO - W1", image: "/images/products/wooden/TRO-W1.jpg", size: '11x6" inch' },
    { id: "TRO-W2", name: "TRO - W2", image: "/images/products/wooden/TRO-W2.jpg", size: '7x9" inch' },
    { id: "TRO-W3", name: "TRO - W3", image: "/images/products/wooden/TRO-W3.jpg", size: '8" inch' },
    { id: "TRO-W5", name: "TRO - W5", image: "/images/products/wooden/TRO-W5.jpg", size: '9"X9" inch' },
    { id: "TRO-W7", name: "TRO - W7", image: "/images/products/wooden/TRO-W7.jpg", size: '10x4" inch' },
    { id: "TRO-W8", name: "TRO - W8", image: "/images/products/wooden/TRO-W8.jpg", size: '10"X10" inch' },
    { id: "TRO-W9", name: "TRO - W9", image: "/images/products/wooden/TRO-W9.jpg", size: '10"X4.5" inch' },
    { id: "TRO-W10", name: "TRO - W10", image: "/images/products/wooden/TRO-W10.jpg", size: '7"X9" inch' },
    { id: "TRO-W11", name: "TRO - W11", image: "/images/products/wooden/TRO-W11.jpg", size: '10x8" inch' },
    { id: "TRO-W12", name: "TRO - W12", image: "/images/products/wooden/TRO-W12.jpg", size: '8"x8" inch' },
    { id: "TRO-W13", name: "TRO - W13", image: "/images/products/wooden/TRO-W13.jpg", size: '8"x8" inch' },
    { id: "TRO-W14", name: "TRO - W14", image: "/images/products/wooden/TRO-W14.jpg", size: '9.5"x9.5" inch' },
    { id: "TRO-W15", name: "TRO - W15", image: "/images/products/wooden/TRO-W15.jpg", size: '10"x8" inch' },
    { id: "TRO-W16", name: "TRO - W16", image: "/images/products/wooden/TRO-W16.jpg", size: '11"x6" inch' },
    { id: "TRO-W17", name: "TRO - W17", image: "/images/products/wooden/TRO-W17.jpg", size: '8"x10" inch' },
    { id: "TRO-W18", name: "TRO - W18", image: "/images/products/wooden/TRO-W18.jpg", size: '10.75"x4" inch' },
    { id: "TRO-W19", name: "TRO - W19", image: "/images/products/wooden/TRO-W19.jpg", size: '8"x4" inch' },
    { id: "TRO-W20", name: "TRO - W20", image: "/images/products/wooden/TRO-W20.jpg", size: '6x8" 8x10" 9x12" inch' },
    { id: "TRO-W21", name: "TRO - W21", image: "/images/products/wooden/TRO-W21.jpg", size: '10.5" inch' },
    { id: "TRO-W22", name: "TRO - W22", image: "/images/products/wooden/TRO-W22.jpg", size: '10" inch' },
    { id: "TRO-W23", name: "TRO - W23", image: "/images/products/wooden/TRO-W23.jpg", size: '10"x8" inch' },
    { id: "TRO-W24", name: "TRO - W24", image: "/images/products/wooden/TRO-W24.jpg", size: '9"x9" inch' },
    { id: "TRO-W25", name: "TRO - W25", image: "/images/products/wooden/TRO-W25.jpg", size: '6x8" 8x10" 9x12" 12x16" inch' },
    { id: "TRO-W26", name: "TRO - W26", image: "/images/products/wooden/TRO-W26.jpg", size: '10" inch' },
    { id: "TRO-W27", name: "TRO - W27", image: "/images/products/wooden/TRO-W27.jpg", size: '10"x8" inch' },
    { id: "TRO-W28", name: "TRO - W28", image: "/images/products/wooden/TRO-W28.jpg", size: '10"x8" inch' },
    { id: "TRO-W29", name: "TRO - W29", image: "/images/products/wooden/TRO-W29.jpg", size: '10"x10" inch' },
    { id: "TRO-W30", name: "TRO - W30", image: "/images/products/wooden/TRO-W30.jpg", size: '7"x10" inch' },
    { id: "TRO-W31", name: "TRO - W31", image: "/images/products/wooden/TRO-W31.jpg", size: 'Small / Medium / Big' },
    { id: "TRO-W32", name: "TRO - W32", image: "/images/products/wooden/TRO-W32.jpg", size: '9.5"x9.5" inch' },
    { id: "TRO-W33", name: "TRO - W33", image: "/images/products/wooden/TRO-W33.jpg", size: 'Big / Medium / Small' },
    { id: "TRO-W34", name: "TRO - W34", image: "/images/products/wooden/TRO-W34.jpg", size: '10" inch' },
    { id: "TRO-W35", name: "TRO - W35", image: "/images/products/wooden/TRO-W35.jpg", size: '5.85"x10.8" inch' },
    { id: "TRO-W36", name: "TRO - W36", image: "/images/products/wooden/TRO-W36.jpg", size: '4.75"x9.75" inch' },
    { id: "TRO-W37", name: "TRO - W37", image: "/images/products/wooden/TRO-W37.jpg", size: '5.85"x8.5" inch' },
    { id: "TRO-W38", name: "TRO - W38", image: "/images/products/wooden/TRO-W38.jpg", size: '5.5"x10.5" inch' },
    { id: "TRO-W39", name: "TRO - W39", image: "/images/products/wooden/TRO-W39.jpg", size: '6.85"x9.85" inch' },
    { id: "TRO-W40", name: "TRO - W40", image: "/images/products/wooden/TRO-W40.jpg", size: '5.4"x11" inch' },
    { id: "TRO-W41", name: "TRO - W41", image: "/images/products/wooden/TRO-W41.jpg", size: '10"x8" inch' },
    { id: "TRO-W42", name: "TRO - W42", image: "/images/products/wooden/TRO-W42.jpg", size: '10"x8" inch' },
    { id: "TRO-W43", name: "TRO - W43", image: "/images/products/wooden/TRO-W43.jpg", size: '10x8" 9x12" inch' },
    { id: "TRO-W44", name: "TRO - W44", image: "/images/products/wooden/TRO-W44.jpg", size: '10"x8" inch' },
    { id: "TRO-W45", name: "TRO - W45", image: "/images/products/wooden/TRO-W45.jpg", size: '10"x8" inch' },
    { id: "TRO-W46", name: "TRO - W46", image: "/images/products/wooden/TRO-W46.jpg", size: '10"x8" inch' },
    { id: "TRO-W47", name: "TRO - W47", image: "/images/products/wooden/TRO-W47.jpg", size: '10"x8" inch' },
    { id: "TRO-W48", name: "TRO - W48", image: "/images/products/wooden/TRO-W48.jpg", size: '10"x3" inch' },
    { id: "TRO-W49", name: "TRO - W49", image: "/images/products/wooden/TRO-W49.jpg", size: '10"x4" inch' },
    { id: "TRO-W50", name: "TRO - W50", image: "/images/products/wooden/TRO-W50.jpg", size: '11"x3" inch' },
    { id: "TRO-W51", name: "TRO - W51", image: "/images/products/wooden/TRO-W51.jpg", size: '10"x4" inch' },
    { id: "TRO-W52", name: "TRO - W52", image: "/images/products/wooden/TRO-W52.jpg", size: '11"x3" inch' },
    { id: "TRO-W53", name: "TRO - W53", image: "/images/products/wooden/TRO-W53.jpg", size: '11"x3.5" inch' },
    { id: "TRO-W54", name: "TRO - W54", image: "/images/products/wooden/TRO-W54.jpg", size: '11"x3.5" inch' },
    { id: "TRO-W55", name: "TRO - W55", image: "/images/products/wooden/TRO-W55.jpg", size: '11"x3.5" inch' },
    { id: "TRO-W56", name: "TRO - W56", image: "/images/products/wooden/TRO-W56.jpg", size: '11"x3.5" inch' },
    { id: "TRO-W57", name: "TRO - W57", image: "/images/products/wooden/TRO-W57.jpg", size: '6"x8" 8"x10" 9"x12" inch' },
    { id: "TRO-W58", name: "TRO - W58", image: "/images/products/wooden/TRO-W58.jpg", size: '10"x8" inch' },
    { id: "TRO-W59", name: "TRO - W59", image: "/images/products/wooden/TRO-W59.jpg", size: '10"x4" inch' },
    { id: "TRO-3701", name: "TRO - 3701", image: "/images/products/wooden/TRO-3701.jpg", size: '8"x6" inch' },
    { id: "TRO-3702", name: "TRO - 3702", image: "/images/products/wooden/TRO-3702.jpg", size: '8"x6" inch' },
    { id: "TRO-3716", name: "TRO - 3716", image: "/images/products/wooden/TRO-3716.jpg", size: '8"x10" inch' },
    { id: "TRO-3720", name: "TRO - 3720", image: "/images/products/wooden/TRO-3720.jpg", size: '8"x8" inch' },
    { id: "TRO-3722", name: "TRO - 3722", image: "/images/products/wooden/TRO-3722.jpg", size: '10.5"x4.75" inch' },
    { id: "TRO-3724", name: "TRO - 3724", image: "/images/products/wooden/TRO-3724.jpg", size: '10.5"x4.75" inch' },
    { id: "TRO-3741", name: "TRO - 3741", image: "/images/products/wooden/TRO-3741.jpg", size: '10"x8" inch' },
    { id: "TRO-3743", name: "TRO - 3743", image: "/images/products/wooden/TRO-3743.jpg", size: '11"x75" x13.75" inch' },
    { id: "TRO-3746", name: "TRO - 3746", image: "/images/products/wooden/TRO-3746.jpg", size: '16.75"x14" inch' },
    { id: "TRO-3762", name: "TRO - 3762", image: "/images/products/wooden/TRO-3762.jpg", size: '7.25"x9" inch' },
    { id: "TRO-3774", name: "TRO - 3774", image: "/images/products/wooden/TRO-3774.jpg", size: '12"x10" inch' },
    { id: "TRO-3786", name: "TRO - 3786", image: "/images/products/wooden/TRO-3786.jpg", size: '12"x10" inch' },
    { id: "TRO-3789", name: "TRO - 3789", image: "/images/products/wooden/TRO-3789.jpg", size: '8"x10" inch' },
    { id: "TRO-3790", name: "TRO - 3790", image: "/images/products/wooden/TRO-3790.jpg", size: '10"x12" inch' },
    { id: "TRO-3793", name: "TRO - 3793", image: "/images/products/wooden/TRO-3793.jpg", size: '10.25"x8" inch' },
    { id: "TRO-3796", name: "TRO - 3796", image: "/images/products/wooden/TRO-3796.jpg", size: '8"x8.25" inch' },
    { id: "TRO-3797", name: "TRO - 3797", image: "/images/products/wooden/TRO-3797.jpg", size: '8"x8.5" inch' },
    { id: "TRO-3803", name: "TRO - 3803", image: "/images/products/wooden/TRO-3803.jpg", size: '10.75"x8.75" inch' },
    { id: "TRO-3806", name: "TRO - 3806", image: "/images/products/wooden/TRO-3806.jpg", size: '10"x8" inch' },
    { id: "TRO-3809", name: "TRO - 3809", image: "/images/products/wooden/TRO-3809.jpg", size: '10"x8" inch' },
    { id: "TRO-3810", name: "TRO - 3810", image: "/images/products/wooden/TRO-3810.jpg", size: '12"x9.5" inch' },
    { id: "TRO-3812", name: "TRO - 3812", image: "/images/products/wooden/TRO-3812.jpg", size: '10"x10" inch' },
  ],
  "acrylic-trophy": [
    { id: "TRO-A1", name: "TRO - A1", image: "/images/products/acrylic/TRO-A1.jpg", size: '8.5"x3.5" inch' },
    { id: "TRO-A2", name: "TRO - A2", image: "/images/products/acrylic/TRO-A2.jpg", size: '7.5"x3.75" inch' },
    { id: "TRO-A3", name: "TRO - A3", image: "/images/products/acrylic/TRO-A3.jpg", size: '7"x5.25" inch' },
    { id: "TRO-A4", name: "TRO - A4", image: "/images/products/acrylic/TRO-A4.jpg", size: '8.5"x4.5" inch' },
    { id: "TRO-A5", name: "TRO - A5", image: "/images/products/acrylic/TRO-A5.jpg", size: '10.5"x4.75" inch' },
    { id: "TRO-A6", name: "TRO - A6", image: "/images/products/acrylic/TRO-A6.jpg", size: '10.5" inch' },
    { id: "TRO-A7", name: "TRO - A7", image: "/images/products/acrylic/TRO-A7.jpg", size: '8.5"x7.75" inch' },
    { id: "TRO-A8", name: "TRO - A8", image: "/images/products/acrylic/TRO-A8.jpg", size: '6.5"x6" inch' },
    { id: "TRO-A9", name: "TRO - A9", image: "/images/products/acrylic/TRO-A9.jpg", size: '8.25"x7.5" inch' },
    { id: "TRO-A10", name: "TRO - A10", image: "/images/products/acrylic/TRO-A10.jpg", size: '6.25"x6" inch' },
    { id: "TRO-A11", name: "TRO - A11", image: "/images/products/acrylic/TRO-A11.jpg", size: '6.25"x5.25" inch' },
    { id: "TRO-A12", name: "TRO - A12", image: "/images/products/acrylic/TRO-A12.jpg", size: '9.25" inch' },
    { id: "TRO-A13", name: "TRO - A13", image: "/images/products/acrylic/TRO-A13.jpg", size: '6"x5.75" inch' },
    { id: "TRO-A14", name: "TRO - A14", image: "/images/products/acrylic/TRO-A14.jpg", size: '6.75"x6" inch' },
    { id: "TRO-A15", name: "TRO - A15", image: "/images/products/acrylic/TRO-A15.jpg", size: '7"x6" inch' },
    { id: "TRO-A16", name: "TRO - A16", image: "/images/products/acrylic/TRO-A16.jpg", size: '9.5"x4" inch' },
    { id: "TRO-A17", name: "TRO - A17", image: "/images/products/acrylic/TRO-A17.jpg", size: '13" inch' },
    { id: "TRO-A18", name: "TRO - A18", image: "/images/products/acrylic/TRO-A18.jpg", size: '8.5"x3" inch' },
    { id: "TRO-A19", name: "TRO - A19", image: "/images/products/acrylic/TRO-A19.jpg", size: '8"x7" inch' },
    { id: "TRO-A20", name: "TRO - A20", image: "/images/products/acrylic/TRO-A20.jpg", size: '10"x5" inch' },
    { id: "TRO-A21", name: "TRO - A21", image: "/images/products/acrylic/TRO-A21.jpg", size: '9"x5" inch' },
    { id: "TRO-A22", name: "TRO - A22", image: "/images/products/acrylic/TRO-A22.jpg", size: '10"x4" inch' },
    { id: "TRO-A23", name: "TRO - A23", image: "/images/products/acrylic/TRO-A23.jpg", size: '9"x5" inch' },
    { id: "TRO-A24", name: "TRO - A24", image: "/images/products/acrylic/TRO-A24.jpg", size: '8"x7" inch' },
    { id: "TRO-A25", name: "TRO - A25", image: "/images/products/acrylic/TRO-A25.jpg", size: '10"x4" inch' },
    { id: "TRO-A26", name: "TRO - A26", image: "/images/products/acrylic/TRO-A26.jpg", size: '8"x7" inch' },
    { id: "TRO-A27", name: "TRO - A27", image: "/images/products/acrylic/TRO-A27.jpg", size: '10.75"x5.5" inch' },
    { id: "TRO-A28", name: "TRO - A28", image: "/images/products/acrylic/TRO-A28.jpg", size: '12" inch' },
    { id: "TRO-A29", name: "TRO - A29", image: "/images/products/acrylic/TRO-A29.jpg", size: '7.25"x6.75" inch' },
    { id: "TRO-A30", name: "TRO - A30", image: "/images/products/acrylic/TRO-A30.jpg", size: '9.5"x6.5" inch' },
    { id: "TRO-A31", name: "TRO - A31", image: "/images/products/acrylic/TRO-A31.jpg", size: '7"x7" inch' },
    { id: "TRO-A32", name: "TRO - A32", image: "/images/products/acrylic/TRO-A32.jpg", size: '7"x7" inch' },
    { id: "TRO-A33", name: "TRO - A33", image: "/images/products/acrylic/TRO-A33.jpg", size: '7"x5" inch' },
    { id: "TRO-A34", name: "TRO - A34", image: "/images/products/acrylic/TRO-A34.jpg", size: '7"x7" inch' },
    { id: "TRO-A35", name: "TRO - A35", image: "/images/products/acrylic/TRO-A35.jpg", size: '9"x5" inch' },
    { id: "TRO-A36", name: "TRO - A36", image: "/images/products/acrylic/TRO-A36.jpg", size: '9"x6" inch' },
    { id: "TRO-A37", name: "TRO - A37", image: "/images/products/acrylic/TRO-A37.jpg", size: '9"x4" inch' },
    { id: "TRO-A38", name: "TRO - A38", image: "/images/products/acrylic/TRO-A38.jpg", size: '10"x5" inch' },
    { id: "TRO-A39", name: "TRO - A39", image: "/images/products/acrylic/TRO-A39.jpg", size: '10"x5" inch' },
    { id: "TRO-A40", name: "TRO - A40", image: "/images/products/acrylic/TRO-A40.jpg", size: '10"x4" inch' },
    { id: "TRO-A41", name: "TRO - A41", image: "/images/products/acrylic/TRO-A41.jpg", size: '10"x4" inch' },
    { id: "TRO-A42", name: "TRO - A42", image: "/images/products/acrylic/TRO-A42.jpg", size: '8"x7" inch' },
    { id: "TRO-A43", name: "TRO - A43", image: "/images/products/acrylic/TRO-A43.jpg", size: '8"x6" inch' },
    { id: "TRO-A44", name: "TRO - A44", image: "/images/products/acrylic/TRO-A44.jpg", size: '9"x6" inch' },
    { id: "TRO-A45", name: "TRO - A45", image: "/images/products/acrylic/TRO-A45.jpg", size: '7"x3" inch' },
    { id: "TRO-A46", name: "TRO - A46", image: "/images/products/acrylic/TRO-A46.jpg", size: '8"x5" inch' },
    { id: "TRO-A47", name: "TRO - A47", image: "/images/products/acrylic/TRO-A47.jpg", size: '8"x6" inch' },
    { id: "TRO-A48", name: "TRO - A48", image: "/images/products/acrylic/TRO-A48.jpg", size: '10"x4" inch' },
    { id: "TRO-A49", name: "TRO - A49", image: "/images/products/acrylic/TRO-A49.jpg", size: '8"x5" inch' },
    { id: "TRO-A50", name: "TRO - A50", image: "/images/products/acrylic/TRO-A50.jpg", size: '9"x4" inch' },
    { id: "TRO-A51", name: "TRO - A51", image: "/images/products/acrylic/TRO-A51.jpg", size: '8"x6" inch' },
    { id: "TRO-A52", name: "TRO - A52", image: "/images/products/acrylic/TRO-A52.jpg", size: '9"x5" inch' },
    { id: "TRO-A53", name: "TRO - A53", image: "/images/products/acrylic/TRO-A53.jpg", size: '7"x7" inch' },
    { id: "TRO-A54", name: "TRO - A54", image: "/images/products/acrylic/TRO-A54.jpg", size: '7"x4" inch' },
    { id: "TRO-A55", name: "TRO - A55", image: "/images/products/acrylic/TRO-A55.jpg", size: '8"x5" inch' },
    { id: "TRO-A56", name: "TRO - A56", image: "/images/products/acrylic/TRO-A56.jpg", size: '10"x4" inch' },
    { id: "TRO-A57", name: "TRO - A57", image: "/images/products/acrylic/TRO-A57.jpg", size: '7"x6" inch' },
    { id: "TRO-A58", name: "TRO - A58", image: "/images/products/acrylic/TRO-A58.jpg", size: '9"x5" inch' },
    { id: "TRO-A59", name: "TRO - A59", image: "/images/products/acrylic/TRO-A59.jpg", size: '10"x3" inch' },
    { id: "TRO-A60", name: "TRO - A60", image: "/images/products/acrylic/TRO-A60.jpg", size: '10"x6" inch' },
    { id: "TRO-A61", name: "TRO - A61", image: "/images/products/acrylic/TRO-A61.jpg", size: '10"x5" inch' },
  ],
  "fiber-trophy": [
    { id: "TRO-F1", name: "TRO - F1", image: "/images/products/fiber/TRO-F1.jpg", size: 'A 10" B 8.5" C 7.5" inch' },
    { id: "TRO-F2", name: "TRO - F2", image: "/images/products/fiber/TRO-F2.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F3", name: "TRO - F3", image: "/images/products/fiber/TRO-F3.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F4", name: "TRO - F4", image: "/images/products/fiber/TRO-F4.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F5", name: "TRO - F5", image: "/images/products/fiber/TRO-F5.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F6", name: "TRO - F6", image: "/images/products/fiber/TRO-F6.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F7", name: "TRO - F7", image: "/images/products/fiber/TRO-F7.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F8", name: "TRO - F8", image: "/images/products/fiber/TRO-F8.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F9", name: "TRO - F9", image: "/images/products/fiber/TRO-F9.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F10", name: "TRO - F10", image: "/images/products/fiber/TRO-F10.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F11", name: "TRO - F11", image: "/images/products/fiber/TRO-F11.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F12", name: "TRO - F12", image: "/images/products/fiber/TRO-F12.jpg", size: 'A 10" B 9" C 8" inch' },
    { id: "TRO-F13", name: "TRO - F13", image: "/images/products/fiber/TRO-F13.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F14", name: "TRO - F14", image: "/images/products/fiber/TRO-F14.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F15", name: "TRO - F15", image: "/images/products/fiber/TRO-F15.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F16", name: "TRO - F16", image: "/images/products/fiber/TRO-F16.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F17", name: "TRO - F17", image: "/images/products/fiber/TRO-F17.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F18", name: "TRO - F18", image: "/images/products/fiber/TRO-F18.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F19", name: "TRO - F19", image: "/images/products/fiber/TRO-F19.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F20", name: "TRO - F20", image: "/images/products/fiber/TRO-F20.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F21", name: "TRO - F21", image: "/images/products/fiber/TRO-F21.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F22", name: "TRO - F22", image: "/images/products/fiber/TRO-F22.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F23", name: "TRO - F23", image: "/images/products/fiber/TRO-F23.jpg", size: '9.5" inch' },
    { id: "TRO-F24", name: "TRO - F24", image: "/images/products/fiber/TRO-F24.jpg", size: '8.5" inch' },
    { id: "TRO-F25", name: "TRO - F25", image: "/images/products/fiber/TRO-F25.jpg", size: '8.5" inch' },
    { id: "TRO-F26", name: "TRO - F26", image: "/images/products/fiber/TRO-F26.jpg", size: '8.5" inch' },
    { id: "TRO-F27", name: "TRO - F27", image: "/images/products/fiber/TRO-F27.jpg", size: '8.5" inch' },
    { id: "TRO-F28", name: "TRO - F28", image: "/images/products/fiber/TRO-F28.jpg", size: '10" inch' },
    { id: "TRO-F29", name: "TRO - F29", image: "/images/products/fiber/TRO-F29.jpg", size: '8.5" inch' },
    { id: "TRO-F30", name: "TRO - F30", image: "/images/products/fiber/TRO-F30.jpg", size: '10" inch' },
    { id: "TRO-F31", name: "TRO - F31", image: "/images/products/fiber/TRO-F31.jpg", size: '8.5" inch' },
    { id: "TRO-F32", name: "TRO - F32", image: "/images/products/fiber/TRO-F32.jpg", size: '9.5" inch' },
    { id: "TRO-F33", name: "TRO - F33", image: "/images/products/fiber/TRO-F33.jpg", size: '7.5" inch' },
    { id: "TRO-F34", name: "TRO - F34", image: "/images/products/fiber/TRO-F34.jpg", size: 'A 14" B 13" C 12" inch' },
    { id: "TRO-F35", name: "TRO - F35", image: "/images/products/fiber/TRO-F35.jpg", size: 'A 11.5" B 10.5" C 9.5" inch' },
    { id: "TRO-F36", name: "TRO - F36", image: "/images/products/fiber/TRO-F36.jpg", size: 'A 19" B 17" C 16" inch' },
    { id: "TRO-F37", name: "TRO - F37", image: "/images/products/fiber/TRO-F37.jpg", size: 'A 12.5" B 11.5" C 10" inch' },
    { id: "TRO-F38", name: "TRO - F38", image: "/images/products/fiber/TRO-F38.jpg", size: 'A 13" B 12" C 11" inch' },
    { id: "TRO-F39", name: "TRO - F39", image: "/images/products/fiber/TRO-F39.jpg", size: 'A 13.5" B 12.5" C 11.5" inch' },
    { id: "TRO-F40", name: "TRO - F40", image: "/images/products/fiber/TRO-F40.jpg", size: 'A 13.5" B 12.5" C 11.5" inch' },
    { id: "TRO-F41", name: "TRO - F41", image: "/images/products/fiber/TRO-F41.jpg", size: 'A 13" B 12" C 11" inch' },
    { id: "TRO-F42", name: "TRO - F42", image: "/images/products/fiber/TRO-F42.jpg", size: 'A 16" B 14.5" C 13.5" inch' },
    { id: "TRO-F43", name: "TRO - F43", image: "/images/products/fiber/TRO-F43.jpg", size: 'A 12.5" B 11.5" C 10" inch' },
    { id: "TRO-F44", name: "TRO - F44", image: "/images/products/fiber/TRO-F44.jpg", size: 'A 9.5" B 8" C 7" inch' },
    { id: "TRO-F45", name: "TRO - F45", image: "/images/products/fiber/TRO-F45.jpg", size: 'A 7" B 6" C 5" inch' },
    { id: "TRO-F46", name: "TRO - F46", image: "/images/products/fiber/TRO-F46.jpg", size: 'A 13" B 12" C 11" inch' },
    { id: "TRO-F47", name: "TRO - F47", image: "/images/products/fiber/TRO-F47.jpg", size: 'A 12" B 11" C 10" inch' },
    { id: "TRO-F48", name: "TRO - F48", image: "/images/products/fiber/TRO-F48.jpg", size: 'A 16" B 14.5" C 13.5" inch' },
    { id: "TRO-F49", name: "TRO - F49", image: "/images/products/fiber/TRO-F49.jpg", size: 'A 13.5" B 12.5" C 11.5" inch' },
    { id: "TRO-F50", name: "TRO - F50", image: "/images/products/fiber/TRO-F50.jpg", size: 'A 13" B 12" C 11" inch' },
    { id: "TRO-F51", name: "TRO - F51", image: "/images/products/fiber/TRO-F51.jpg", size: 'A 12" B 11" C 10" inch' },
    { id: "TRO-F52", name: "TRO - F52", image: "/images/products/fiber/TRO-F52.jpg", size: 'A 27" B 23" C 20" inch' },
    { id: "TRO-F53", name: "TRO - F53", image: "/images/products/fiber/TRO-F53.jpg", size: 'A 13" B 12" C 11" inch' },
    { id: "TRO-F54", name: "TRO - F54", image: "/images/products/fiber/TRO-F54.jpg", size: 'A 22" B 20" C 18" inch' },
    { id: "TRO-F55", name: "TRO - F55", image: "/images/products/fiber/TRO-F55.jpg", size: 'A 18" B 16" C 14" inch' },
    { id: "TRO-F56", name: "TRO - F56", image: "/images/products/fiber/TRO-F56.jpg", size: 'A 15" B 14" C 13" inch' },
    { id: "TRO-F57", name: "TRO - F57", image: "/images/products/fiber/TRO-F57.jpg", size: 'A 17" B 17" C 15" inch' },
    { id: "TRO-F58", name: "TRO - F58", image: "/images/products/fiber/TRO-F58.jpg", size: 'A 27" B 24" C 21" inch' },
    { id: "TRO-F59", name: "TRO - F59", image: "/images/products/fiber/TRO-F59.jpg", size: 'A 28" B 25" C 22" inch' },
    { id: "TRO-F60", name: "TRO - F60", image: "/images/products/fiber/TRO-F60.jpg", size: 'A 28" B 25" C 22" inch' },
    { id: "TRO-F61", name: "TRO - F61", image: "/images/products/fiber/TRO-F61.jpg", size: 'A 33" B 30" C 22" inch' },
    { id: "TRO-F62", name: "TRO - F62", image: "/images/products/fiber/TRO-F62.jpg", size: 'A 12" B 11" C 10" inch' },
    { id: "TRO-F63", name: "TRO - F63", image: "/images/products/fiber/TRO-F63.jpg", size: 'A 15" B 14" C 13" inch' },
    { id: "TRO-F64", name: "TRO - F64", image: "/images/products/fiber/TRO-F64.jpg", size: 'A 22" B 20" C 18" inch' },
    { id: "TRO-F65", name: "TRO - F65", image: "/images/products/fiber/TRO-F65.jpg", size: 'A 25" B 23" C 21" inch' },
    { id: "TRO-F66", name: "TRO - F66", image: "/images/products/fiber/TRO-F66.jpg", size: 'A 12" B 10.5" C 9" inch' },
    { id: "TRO-F67", name: "TRO - F67", image: "/images/products/fiber/TRO-F67.jpg", size: 'A 14" B 13" C 12" inch' },
    { id: "TRO-F68", name: "TRO - F68", image: "/images/products/fiber/TRO-F68.jpg", size: 'A 14.5" B 13" C 11.5" inch' },
    { id: "TRO-F69", name: "TRO - F69", image: "/images/products/fiber/TRO-F69.jpg", size: 'A 14" B 12.5" C 11" inch' },
    { id: "TRO-F70", name: "TRO - F70", image: "/images/products/fiber/TRO-F70.jpg", size: 'A 14" B 13" C 12" inch' },
    { id: "TRO-F71", name: "TRO - F71", image: "/images/products/fiber/TRO-F71.jpg", size: 'A 18" B 17" C 15" inch' },
    { id: "TRO-F72", name: "TRO - F72", image: "/images/products/fiber/TRO-F72.jpg", size: 'A 9" B 7.5" C 6.5" inch' },
    { id: "TRO-F73", name: "TRO - F73", image: "/images/products/fiber/TRO-F73.jpg", size: 'A 11.5" B 10" C 9" inch' },
    { id: "TRO-F74", name: "TRO - F74", image: "/images/products/fiber/TRO-F74.jpg", size: 'A 15" B 13.5" C 11.5" inch' },
    { id: "TRO-F75", name: "TRO - F75", image: "/images/products/fiber/TRO-F75.jpg", size: 'A 14" B 12.5" C 11.5" inch' },
    { id: "TRO-F76", name: "TRO - F76", image: "/images/products/fiber/TRO-F76.jpg", size: 'A 12" B 10.5" C 9.5" inch' },
    { id: "TRO-F77", name: "TRO - F77", image: "/images/products/fiber/TRO-F77.jpg", size: 'A 14" B 13" C 12" inch' },
    { id: "TRO-F78", name: "TRO - F78", image: "/images/products/fiber/TRO-F78.jpg", size: 'A 11.5" B 10.5" C 9.5" inch' },
    { id: "TRO-F79", name: "TRO - F79", image: "/images/products/fiber/TRO-F79.jpg", size: 'A 12" B 11" C 10" inch' },
    { id: "TRO-F80", name: "TRO - F80", image: "/images/products/fiber/TRO-F80.jpg", size: '10" inch' },
    { id: "TRO-F81", name: "TRO - F81", image: "/images/products/fiber/TRO-F81.jpg", size: '8" inch' },
    { id: "TRO-F82", name: "TRO - F82", image: "/images/products/fiber/TRO-F82.jpg", size: '8" inch' },
    { id: "TRO-F83", name: "TRO - F83", image: "/images/products/fiber/TRO-F83.jpg", size: '7" inch' },
    { id: "TRO-F84", name: "TRO - F84", image: "/images/products/fiber/TRO-F84.jpg", size: '7" inch' },
    { id: "TRO-F85", name: "TRO - F85", image: "/images/products/fiber/TRO-F85.jpg", size: 'A 13.5" B 12.5" C 11" inch' },
    { id: "TRO-F86", name: "TRO - F86", image: "/images/products/fiber/TRO-F86.jpg", size: 'A 11.5" B 10.5" C 9" inch' },
    { id: "TRO-F87", name: "TRO - F87", image: "/images/products/fiber/TRO-F87.jpg", size: 'A 14" B 13" C 12" inch' },
    { id: "TRO-F88", name: "TRO - F88", image: "/images/products/fiber/TRO-F88.jpg", size: 'A 12.5" B 11" C 10" inch' },
    { id: "TRO-F89", name: "TRO - F89", image: "/images/products/fiber/TRO-F89.jpg", size: 'A 22" B 20" C 18" inch' },
    { id: "TRO-F90", name: "TRO - F90", image: "/images/products/fiber/TRO-F90.jpg", size: 'A 16" B 14" C 12" inch' },
    { id: "TRO-F91", name: "TRO - F91", image: "/images/products/fiber/TRO-F91.jpg", size: '27" inch' },
    { id: "TRO-F92", name: "TRO - F92", image: "/images/products/fiber/TRO-F92.jpg", size: '30" inch' },
    { id: "TRO-F93", name: "TRO - F93", image: "/images/products/fiber/TRO-F93.jpg", size: 'A 25" B 23" C 21" inch' },
    { id: "TRO-F94", name: "TRO - F94", image: "/images/products/fiber/TRO-F94.jpg", size: 'A 20" B 18" C 16" inch' },
    { id: "TRO-F95", name: "TRO - F95", image: "/images/products/fiber/TRO-F95.jpg", size: 'A 12" B 11" C 10" inch' },
    { id: "TRO-F96", name: "TRO - F96", image: "/images/products/fiber/TRO-F96.jpg", size: 'A 12" B 11" C 10" inch' },
    { id: "TRO-F97", name: "TRO - F97", image: "/images/products/fiber/TRO-F97.jpg", size: 'A 12" B 11" C 10" inch' },
    { id: "TRO-F98", name: "TRO - F98", image: "/images/products/fiber/TRO-F98.jpg", size: 'A 13" B 12" C 11" inch' },
    { id: "TRO-F99", name: "TRO - F99", image: "/images/products/fiber/TRO-F99.jpg", size: '8.25" inch' },
    { id: "TRO-F100", name: "TRO - F100", image: "/images/products/fiber/TRO-F100.jpg", size: '8.5" inch' },
    { id: "TRO-F101", name: "TRO - F101", image: "/images/products/fiber/TRO-F101.jpg", size: '8.5" inch' },
    { id: "TRO-F102", name: "TRO - F102", image: "/images/products/fiber/TRO-F102.jpg", size: 'A 11.5" B 10.5" C 9.5" inch' },
    { id: "TRO-F103", name: "TRO - F103", image: "/images/products/fiber/TRO-F103.jpg", size: 'A 11.25" B 10.5" C 9.5" inch' },
    { id: "TRO-F104", name: "TRO - F104", image: "/images/products/fiber/TRO-F104.jpg", size: 'A 11" B 10" C 9" inch' },
    { id: "TRO-F105", name: "TRO - F105", image: "/images/products/fiber/TRO-F105.jpg", size: 'A 11.25" B 10.5" C 9.5" inch' },
    { id: "TRO-F106", name: "TRO - F106", image: "/images/products/fiber/TRO-F106.jpg", size: 'A 11" B 10" C 9" inch' },
    { id: "TRO-F107", name: "TRO - F107", image: "/images/products/fiber/TRO-F107.jpg", size: 'A 12" B 11" C 10" inch' },
    { id: "TRO-F108", name: "TRO - F108", image: "/images/products/fiber/TRO-F108.jpg", size: 'A 11.5" B 10.5" C 9.5" inch' },
    { id: "TRO-F500", name: "TRO - F500", image: "/images/products/fiber/TRO-F500.jpg", size: '13" inch' },
    { id: "TRO-F501", name: "TRO - F501", image: "/images/products/fiber/TRO-F501.jpg", size: '12" inch' },
    { id: "TRO-F502", name: "TRO - F502", image: "/images/products/fiber/TRO-F502.jpg", size: '11.5" inch' },
    { id: "TRO-F503", name: "TRO - F503", image: "/images/products/fiber/TRO-F503.jpg", size: '13" inch' },
    { id: "TRO-F506", name: "TRO - F506", image: "/images/products/fiber/TRO-F506.jpg", size: '11.5" inch' },
    { id: "TRO-F507", name: "TRO - F507", image: "/images/products/fiber/TRO-F507.jpg", size: 'A 12" B 11.5" C 11" inch' },
    { id: "TRO-F508", name: "TRO - F508", image: "/images/products/fiber/TRO-F508.jpg", size: 'A 13.5" B 12.5" C 11.5" inch' },
    { id: "TRO-F509", name: "TRO - F509", image: "/images/products/fiber/TRO-F509.jpg", size: 'A 15.25" B 14.25" C 13.25" inch' },
    { id: "TRO-F510", name: "TRO - F510", image: "/images/products/fiber/TRO-F510.jpg", size: 'A 16" B 15" C 14" inch' },
    { id: "TRO-F511", name: "TRO - F511", image: "/images/products/fiber/TRO-F511.jpg", size: '8.5" inch' },
    { id: "TRO-F512", name: "TRO - F512", image: "/images/products/fiber/TRO-F512.jpg", size: '13.5" inch' },
    { id: "TRO-F513", name: "TRO - F513", image: "/images/products/fiber/TRO-F513.jpg", size: '8" inch' },
    { id: "TRO-F514", name: "TRO - F514", image: "/images/products/fiber/TRO-F514.jpg", size: '11.5" inch' },
    { id: "TRO-F515", name: "TRO - F515", image: "/images/products/fiber/TRO-F515.jpg", size: '14.5" inch' },
    { id: "TRO-F516", name: "TRO - F516", image: "/images/products/fiber/TRO-F516.jpg", size: '12.5" inch' },
    { id: "TRO-F517", name: "TRO - F517", image: "/images/products/fiber/TRO-F517.jpg", size: 'A 14.5" B 13.5" C 12.5" inch' },
    { id: "TRO-F518", name: "TRO - F518", image: "/images/products/fiber/TRO-F518.jpg", size: '10.5" inch' },
    { id: "TRO-F519", name: "TRO - F519", image: "/images/products/fiber/TRO-F519.jpg", size: '12.5" inch' },
    { id: "TRO-F520", name: "TRO - F520", image: "/images/products/fiber/TRO-F520.jpg", size: '10.5" inch' },
    { id: "TRO-F700", name: "TRO - F700", image: "/images/products/fiber/TRO-F700.jpg", size: '11" inch' },
    { id: "TRO-F701", name: "TRO - F701", image: "/images/products/fiber/TRO-F701.jpg", size: '11" inch' },
    { id: "TRO-F702", name: "TRO - F702", image: "/images/products/fiber/TRO-F702.jpg", size: '11" inch' },
    { id: "TRO-F703", name: "TRO - F703", image: "/images/products/fiber/TRO-F703.jpg", size: '11" inch' },
    { id: "TRO-F704", name: "TRO - F704", image: "/images/products/fiber/TRO-F704.jpg", size: '11" inch' },
    { id: "TRO-F705", name: "TRO - F705", image: "/images/products/fiber/TRO-F705.jpg", size: '11" inch' },
    { id: "TRO-F706", name: "TRO - F706", image: "/images/products/fiber/TRO-F706.jpg", size: '11" inch' },
    { id: "TRO-F707", name: "TRO - F707", image: "/images/products/fiber/TRO-F707.jpg", size: '11" inch' },
    { id: "TRO-F708", name: "TRO - F708", image: "/images/products/fiber/TRO-F708.jpg", size: '11" inch' },
  ],
  "metal-trophy": [
    { id: "TRO-M56", name: "TRO - M56", image: "/images/products/metal/TRO-M56.jpg", size: '4x13.75" inch' },
    { id: "TRO-M367", name: "TRO - M367", image: "/images/products/metal/TRO-M367.jpg", size: '4x12" inch' },
    { id: "TRO-M371", name: "TRO - M371", image: "/images/products/metal/TRO-M371.jpg", size: '4x12" inch' },
    { id: "TRO-M372", name: "TRO - M372", image: "/images/products/metal/TRO-M372.jpg", size: '7.25" inch' },
    { id: "TRO-M373", name: "TRO - M373", image: "/images/products/metal/TRO-M373.jpg", size: '7" inch' },
    { id: "TRO-M374", name: "TRO - M374", image: "/images/products/metal/TRO-M374.jpg", size: '13" inch' },
    { id: "TRO-M348", name: "TRO - M348", image: "/images/products/metal/TRO-M348.jpg", size: '11" inch' },
    { id: "TRO-M383", name: "TRO - M383", image: "/images/products/metal/TRO-M383.jpg", size: 'A 13" B 11.5" C 10" inch' },
    { id: "TRO-M504", name: "TRO - M504", image: "/images/products/metal/TRO-M504.jpg", size: 'A 14" B 12.5" C 11" inch' },
    { id: "TRO-M520", name: "TRO - M520", image: "/images/products/metal/TRO-M520.jpg", size: 'A 13" B 11.5" C 10" D 7" inch' },
    { id: "TRO-M569", name: "TRO - M569", image: "/images/products/metal/TRO-M569.jpg", size: 'A 12" B 10.5" C 9" inch' },
    { id: "TRO-M602", name: "TRO - M602", image: "/images/products/metal/TRO-M602.jpg", size: '14.5" inch' },
    { id: "TRO-M633", name: "TRO - M633", image: "/images/products/metal/TRO-M633.jpg", size: 'A 14.5" B 13" C 11.5" inch' },
    { id: "TRO-M634", name: "TRO - M634", image: "/images/products/metal/TRO-M634.jpg", size: '9.25" inch' },
    { id: "TRO-M635", name: "TRO - M635", image: "/images/products/metal/TRO-M635.jpg", size: '9.25" inch' },
    { id: "TRO-M637", name: "TRO - M637", image: "/images/products/metal/TRO-M637.jpg", size: 'A 15" B 13.5" C 12" inch' },
    { id: "TRO-M643", name: "TRO - M643", image: "/images/products/metal/TRO-M643.jpg", size: '10" inch' },
    { id: "TRO-M650", name: "TRO - M650", image: "/images/products/metal/TRO-M650.jpg", size: '13.5" inch' },
    { id: "TRO-M652", name: "TRO - M652", image: "/images/products/metal/TRO-M652.jpg", size: '12" inch' },
    { id: "TRO-M654", name: "TRO - M654", image: "/images/products/metal/TRO-M654.jpg", size: 'A 13.5" B 12" C 10.5" inch' },
    { id: "TRO-M662", name: "TRO - M662", image: "/images/products/metal/TRO-M662.jpg", size: '14" inch' },
    { id: "TRO-M665", name: "TRO - M665", image: "/images/products/metal/TRO-M665.jpg", size: '12" inch' },
    { id: "TRO-M667", name: "TRO - M667", image: "/images/products/metal/TRO-M667.jpg", size: '11" inch' },
    { id: "TRO-M671", name: "TRO - M671", image: "/images/products/metal/TRO-M671.jpg", size: '10" inch' },
    { id: "TRO-M683", name: "TRO - M683", image: "/images/products/metal/TRO-M683.jpg", size: '12" inch' },
    { id: "TRO-M687", name: "TRO - M687", image: "/images/products/metal/TRO-M687.jpg", size: '13" inch' },
    { id: "TRO-M688", name: "TRO - M688", image: "/images/products/metal/TRO-M688.jpg", size: '12" inch' },
    { id: "TRO-M689", name: "TRO - M689", image: "/images/products/metal/TRO-M689.jpg", size: 'A 13.5" B 12" C 10.5" inch' },
    { id: "TRO-M697", name: "TRO - M697", image: "/images/products/metal/TRO-M697.jpg", size: 'A 14.5" B 13" C 11.5" inch' },
    { id: "TRO-M704", name: "TRO - M704", image: "/images/products/metal/TRO-M704.jpg", size: 'A 11" B 10.5" C 9" inch' },
    { id: "TRO-M705", name: "TRO - M705", image: "/images/products/metal/TRO-M705.jpg", size: '11" inch' },
    { id: "TRO-M723", name: "TRO - M723", image: "/images/products/metal/TRO-M723.jpg", size: '12" inch' },
  ],
  "sports-medals": [],
  "corporate-gifts": [],
};

export const CITIES = [
  { slug: "delhi", name: "Delhi" },
  { slug: "noida", name: "Noida" },
  { slug: "gurgaon", name: "Gurgaon" },
  { slug: "ghaziabad", name: "Ghaziabad" },
  { slug: "faridabad", name: "Faridabad" },
] as const;
