export const PHONE_1 = "9310651066";
export const PHONE_2 = "9315879315";
export const EMAIL = "xpertawards23@gmail.com";
export const WHATSAPP_URL = `https://wa.me/91${PHONE_1}?text=Hi%20Xpert%20Awards%2C%20I%20am%20interested%20in%20your%20products.`;
export const ADDRESS = "Shop No. - 2/73, GF, Lalita Park, Near Gurudwara, Laxmi Nagar, New Delhi, 110092";

export const CATEGORIES = [
  {
    slug: "wooden-trophy",
    title: "Wooden Trophy",
    description: "Personalized trophies designed to celebrate unique achievements with premium materials and craftsmanship.",
    material: "Premium Wood with Metal/Gold Plating",
  },
  {
    slug: "acrylic-trophy",
    title: "Acrylic Trophy",
    description: "Corporate and academic recognition pieces that honor excellence and motivate continued success.",
    material: "High-grade Acrylic Crystal",
  },
  {
    slug: "fiber-trophy",
    title: "Fiber Trophy",
    description: "Grand championship trophies and awards for sporting events, competitions, and tournaments.",
    material: "Durable Fiber with Gold/Silver Finish",
  },
  {
    slug: "metal-trophy",
    title: "Metal Trophy",
    description: "High-quality metal trophies designed to showcase remarkable achievements with lasting elegance.",
    material: "Brass / Stainless Steel / Zinc Alloy",
  },
  {
    slug: "sports-medals",
    title: "Sports Medals",
    description: "Elegant and customizable medals perfect for corporate events, clients, and employee recognition.",
    material: "Metal with Custom Ribbon",
  },
  {
    slug: "corporate-gifts",
    title: "Corporate Gifts",
    description: "Complete award solutions for schools, colleges, and large-scale events with custom branding.",
    material: "Mixed Premium Materials",
  },
] as const;

export interface ProductItem {
  id: string;
  name: string;
  image: string;
  size: string;
}

export const PRODUCT_ITEMS: Record<string, ProductItem[]> = {
  "wooden-trophy": [
    { id: "TRO-W1", name: "TRO - W1", image: "/images/products/wooden/TRO-W1.jpg", size: '11x6" inch' },
    { id: "TRO-W2", name: "TRO - W2", image: "/images/products/wooden/TRO-W2.jpg", size: '7x9" inch' },
    { id: "TRO-W3", name: "TRO - W3", image: "/images/products/wooden/TRO-W3.jpg", size: '8" inch' },
    { id: "TRO-W5", name: "TRO - W5", image: "/images/products/wooden/TRO-W5.jpg", size: '9"X9" inch' },
    { id: "TRO-W7", name: "TRO - W7", image: "/images/products/wooden/TRO-W7.jpg", size: '10x4" inch' },
    { id: "TRO-W8", name: "TRO - W8", image: "/images/products/wooden/TRO-W8.jpg", size: '10"X10" inch' },
    { id: "TRO-W9", name: "TRO - W9", image: "/images/products/wooden/TRO-W9.jpg", size: '10"X4.5" inch' },
    { id: "TRO-W10", name: "TRO - W10", image: "/images/products/wooden/TRO-W10.jpg", size: '7"X9" inch' },
    { id: "TRO-W11", name: "TRO - W11", image: "/images/products/wooden/TRO-W11.jpg", size: '10x8" inch' },
    { id: "TRO-W12", name: "TRO - W12", image: "/images/products/wooden/TRO-W12.jpg", size: '8"x8" inch' },
    { id: "TRO-W13", name: "TRO - W13", image: "/images/products/wooden/TRO-W13.jpg", size: '8"x8" inch' },
    { id: "TRO-W14", name: "TRO - W14", image: "/images/products/wooden/TRO-W14.jpg", size: '9.5"x9.5" inch' },
    { id: "TRO-W15", name: "TRO - W15", image: "/images/products/wooden/TRO-W15.jpg", size: '10"x8" inch' },
    { id: "TRO-W16", name: "TRO - W16", image: "/images/products/wooden/TRO-W16.jpg", size: '11"x6" inch' },
    { id: "TRO-W17", name: "TRO - W17", image: "/images/products/wooden/TRO-W17.jpg", size: '8"x10" inch' },
    { id: "TRO-W18", name: "TRO - W18", image: "/images/products/wooden/TRO-W18.jpg", size: '10.75"x4" inch' },
    { id: "TRO-W19", name: "TRO - W19", image: "/images/products/wooden/TRO-W19.jpg", size: '8"x4" inch' },
    { id: "TRO-W20", name: "TRO - W20", image: "/images/products/wooden/TRO-W20.jpg", size: '6x8" 8x10" 9x12" inch' },
    { id: "TRO-W21", name: "TRO - W21", image: "/images/products/wooden/TRO-W21.jpg", size: '10.5" inch' },
    { id: "TRO-W22", name: "TRO - W22", image: "/images/products/wooden/TRO-W22.jpg", size: '10" inch' },
    { id: "TRO-W23", name: "TRO - W23", image: "/images/products/wooden/TRO-W23.jpg", size: '10"x8" inch' },
    { id: "TRO-W24", name: "TRO - W24", image: "/images/products/wooden/TRO-W24.jpg", size: '9"x9" inch' },
    { id: "TRO-W25", name: "TRO - W25", image: "/images/products/wooden/TRO-W25.jpg", size: '6x8" 8x10" 9x12" 12x16" inch' },
    { id: "TRO-W26", name: "TRO - W26", image: "/images/products/wooden/TRO-W26.jpg", size: '10" inch' },
    { id: "TRO-W27", name: "TRO - W27", image: "/images/products/wooden/TRO-W27.jpg", size: '10"x8" inch' },
    { id: "TRO-W28", name: "TRO - W28", image: "/images/products/wooden/TRO-W28.jpg", size: '10"x8" inch' },
    { id: "TRO-W29", name: "TRO - W29", image: "/images/products/wooden/TRO-W29.jpg", size: '10"x10" inch' },
    { id: "TRO-W30", name: "TRO - W30", image: "/images/products/wooden/TRO-W30.jpg", size: '7"x10" inch' },
    { id: "TRO-W31", name: "TRO - W31", image: "/images/products/wooden/TRO-W31.jpg", size: 'Small / Medium / Big' },
    { id: "TRO-W32", name: "TRO - W32", image: "/images/products/wooden/TRO-W32.jpg", size: '9.5"x9.5" inch' },
    { id: "TRO-W33", name: "TRO - W33", image: "/images/products/wooden/TRO-W33.jpg", size: 'Big / Medium / Small' },
    { id: "TRO-W34", name: "TRO - W34", image: "/images/products/wooden/TRO-W34.jpg", size: '10" inch' },
    { id: "TRO-W35", name: "TRO - W35", image: "/images/products/wooden/TRO-W35.jpg", size: '5.85"x10.8" inch' },
    { id: "TRO-W36", name: "TRO - W36", image: "/images/products/wooden/TRO-W36.jpg", size: '4.75"x9.75" inch' },
    { id: "TRO-W37", name: "TRO - W37", image: "/images/products/wooden/TRO-W37.jpg", size: '5.85"x8.5" inch' },
    { id: "TRO-W38", name: "TRO - W38", image: "/images/products/wooden/TRO-W38.jpg", size: '5.5"x10.5" inch' },
    { id: "TRO-W39", name: "TRO - W39", image: "/images/products/wooden/TRO-W39.jpg", size: '6.85"x9.85" inch' },
    { id: "TRO-W40", name: "TRO - W40", image: "/images/products/wooden/TRO-W40.jpg", size: '5.4"x11" inch' },
    { id: "TRO-W41", name: "TRO - W41", image: "/images/products/wooden/TRO-W41.jpg", size: '10"x8" inch' },
    { id: "TRO-W42", name: "TRO - W42", image: "/images/products/wooden/TRO-W42.jpg", size: '10"x8" inch' },
    { id: "TRO-W43", name: "TRO - W43", image: "/images/products/wooden/TRO-W43.jpg", size: '10x8" 9x12" inch' },
    { id: "TRO-W44", name: "TRO - W44", image: "/images/products/wooden/TRO-W44.jpg", size: '10"x8" inch' },
    { id: "TRO-W45", name: "TRO - W45", image: "/images/products/wooden/TRO-W45.jpg", size: '10"x8" inch' },
    { id: "TRO-W46", name: "TRO - W46", image: "/images/products/wooden/TRO-W46.jpg", size: '10"x8" inch' },
    { id: "TRO-W47", name: "TRO - W47", image: "/images/products/wooden/TRO-W47.jpg", size: '10"x8" inch' },
    { id: "TRO-W48", name: "TRO - W48", image: "/images/products/wooden/TRO-W48.jpg", size: '10"x3" inch' },
    { id: "TRO-W49", name: "TRO - W49", image: "/images/products/wooden/TRO-W49.jpg", size: '10"x4" inch' },
    { id: "TRO-W50", name: "TRO - W50", image: "/images/products/wooden/TRO-W50.jpg", size: '11"x3" inch' },
    { id: "TRO-W51", name: "TRO - W51", image: "/images/products/wooden/TRO-W51.jpg", size: '10"x4" inch' },
    { id: "TRO-W52", name: "TRO - W52", image: "/images/products/wooden/TRO-W52.jpg", size: '11"x3" inch' },
    { id: "TRO-W53", name: "TRO - W53", image: "/images/products/wooden/TRO-W53.jpg", size: '11"x3.5" inch' },
    { id: "TRO-W54", name: "TRO - W54", image: "/images/products/wooden/TRO-W54.jpg", size: '11"x3.5" inch' },
    { id: "TRO-W55", name: "TRO - W55", image: "/images/products/wooden/TRO-W55.jpg", size: '11"x3.5" inch' },
    { id: "TRO-W56", name: "TRO - W56", image: "/images/products/wooden/TRO-W56.jpg", size: '11"x3.5" inch' },
    { id: "TRO-W57", name: "TRO - W57", image: "/images/products/wooden/TRO-W57.jpg", size: '6"x8" 8"x10" 9"x12" inch' },
    { id: "TRO-W58", name: "TRO - W58", image: "/images/products/wooden/TRO-W58.jpg", size: '10"x8" inch' },
    { id: "TRO-W59", name: "TRO - W59", image: "/images/products/wooden/TRO-W59.jpg", size: '10"x4" inch' },
    { id: "TRO-3701", name: "TRO - 3701", image: "/images/products/wooden/TRO-3701.jpg", size: '8"x6" inch' },
    { id: "TRO-3702", name: "TRO - 3702", image: "/images/products/wooden/TRO-3702.jpg", size: '8"x6" inch' },
    { id: "TRO-3716", name: "TRO - 3716", image: "/images/products/wooden/TRO-3716.jpg", size: '8"x10" inch' },
    { id: "TRO-3720", name: "TRO - 3720", image: "/images/products/wooden/TRO-3720.jpg", size: '8"x8" inch' },
    { id: "TRO-3722", name: "TRO - 3722", image: "/images/products/wooden/TRO-3722.jpg", size: '10.5"x4.75" inch' },
    { id: "TRO-3724", name: "TRO - 3724", image: "/images/products/wooden/TRO-3724.jpg", size: '10.5"x4.75" inch' },
    { id: "TRO-3741", name: "TRO - 3741", image: "/images/products/wooden/TRO-3741.jpg", size: '10"x8" inch' },
    { id: "TRO-3743", name: "TRO - 3743", image: "/images/products/wooden/TRO-3743.jpg", size: '11"x75" x13.75" inch' },
    { id: "TRO-3746", name: "TRO - 3746", image: "/images/products/wooden/TRO-3746.jpg", size: '16.75"x14" inch' },
    { id: "TRO-3762", name: "TRO - 3762", image: "/images/products/wooden/TRO-3762.jpg", size: '7.25"x9" inch' },
    { id: "TRO-3774", name: "TRO - 3774", image: "/images/products/wooden/TRO-3774.jpg", size: '12"x10" inch' },
    { id: "TRO-3786", name: "TRO - 3786", image: "/images/products/wooden/TRO-3786.jpg", size: '12"x10" inch' },
    { id: "TRO-3789", name: "TRO - 3789", image: "/images/products/wooden/TRO-3789.jpg", size: '8"x10" inch' },
    { id: "TRO-3790", name: "TRO - 3790", image: "/images/products/wooden/TRO-3790.jpg", size: '10"x12" inch' },
    { id: "TRO-3793", name: "TRO - 3793", image: "/images/products/wooden/TRO-3793.jpg", size: '10.25"x8" inch' },
    { id: "TRO-3796", name: "TRO - 3796", image: "/images/products/wooden/TRO-3796.jpg", size: '8"x8.25" inch' },
    { id: "TRO-3797", name: "TRO - 3797", image: "/images/products/wooden/TRO-3797.jpg", size: '8"x8.5" inch' },
    { id: "TRO-3803", name: "TRO - 3803", image: "/images/products/wooden/TRO-3803.jpg", size: '10.75"x8.75" inch' },
    { id: "TRO-3806", name: "TRO - 3806", image: "/images/products/wooden/TRO-3806.jpg", size: '10"x8" inch' },
    { id: "TRO-3809", name: "TRO - 3809", image: "/images/products/wooden/TRO-3809.jpg", size: '10"x8" inch' },
    { id: "TRO-3810", name: "TRO - 3810", image: "/images/products/wooden/TRO-3810.jpg", size: '12"x9.5" inch' },
    { id: "TRO-3812", name: "TRO - 3812", image: "/images/products/wooden/TRO-3812.jpg", size: '10"x10" inch' },
  ],
  "acrylic-trophy": [
    { id: "TRO-A1", name: "TRO - A1", image: "/images/products/acrylic/TRO-A1.jpg", size: '8.5"x3.5" inch' },
    { id: "TRO-A2", name: "TRO - A2", image: "/images/products/acrylic/TRO-A2.jpg", size: '7.5"x3.75" inch' },
    { id: "TRO-A3", name: "TRO - A3", image: "/images/products/acrylic/TRO-A3.jpg", size: '7"x5.25" inch' },
    { id: "TRO-A4", name: "TRO - A4", image: "/images/products/acrylic/TRO-A4.jpg", size: '8.5"x4.5" inch' },
    { id: "TRO-A5", name: "TRO - A5", image: "/images/products/acrylic/TRO-A5.jpg", size: '10.5"x4.75" inch' },
    { id: "TRO-A6", name: "TRO - A6", image: "/images/products/acrylic/TRO-A6.jpg", size: '10.5" inch' },
    { id: "TRO-A7", name: "TRO - A7", image: "/images/products/acrylic/TRO-A7.jpg", size: '8.5"x7.75" inch' },
    { id: "TRO-A8", name: "TRO - A8", image: "/images/products/acrylic/TRO-A8.jpg", size: '6.5"x6" inch' },
    { id: "TRO-A9", name: "TRO - A9", image: "/images/products/acrylic/TRO-A9.jpg", size: '8.25"x7.5" inch' },
    { id: "TRO-A10", name: "TRO - A10", image: "/images/products/acrylic/TRO-A10.jpg", size: '6.25"x6" inch' },
    { id: "TRO-A11", name: "TRO - A11", image: "/images/products/acrylic/TRO-A11.jpg", size: '6.25"x5.25" inch' },
    { id: "TRO-A12", name: "TRO - A12", image: "/images/products/acrylic/TRO-A12.jpg", size: '9.25" inch' },
    { id: "TRO-A13", name: "TRO - A13", image: "/images/products/acrylic/TRO-A13.jpg", size: '6"x5.75" inch' },
    { id: "TRO-A14", name: "TRO - A14", image: "/images/products/acrylic/TRO-A14.jpg", size: '6.75"x6" inch' },
    { id: "TRO-A15", name: "TRO - A15", image: "/images/products/acrylic/TRO-A15.jpg", size: '7"x6" inch' },
    { id: "TRO-A16", name: "TRO - A16", image: "/images/products/acrylic/TRO-A16.jpg", size: '9.5"x4" inch' },
    { id: "TRO-A17", name: "TRO - A17", image: "/images/products/acrylic/TRO-A17.jpg", size: '13" inch' },
    { id: "TRO-A18", name: "TRO - A18", image: "/images/products/acrylic/TRO-A18.jpg", size: '8.5"x3" inch' },
    { id: "TRO-A19", name: "TRO - A19", image: "/images/products/acrylic/TRO-A19.jpg", size: '8"x7" inch' },
    { id: "TRO-A20", name: "TRO - A20", image: "/images/products/acrylic/TRO-A20.jpg", size: '10"x5" inch' },
    { id: "TRO-A21", name: "TRO - A21", image: "/images/products/acrylic/TRO-A21.jpg", size: '9"x5" inch' },
    { id: "TRO-A22", name: "TRO - A22", image: "/images/products/acrylic/TRO-A22.jpg", size: '10"x4" inch' },
    { id: "TRO-A23", name: "TRO - A23", image: "/images/products/acrylic/TRO-A23.jpg", size: '9"x5" inch' },
    { id: "TRO-A24", name: "TRO - A24", image: "/images/products/acrylic/TRO-A24.jpg", size: '8"x7" inch' },
    { id: "TRO-A25", name: "TRO - A25", image: "/images/products/acrylic/TRO-A25.jpg", size: '10"x4" inch' },
    { id: "TRO-A26", name: "TRO - A26", image: "/images/products/acrylic/TRO-A26.jpg", size: '8"x7" inch' },
    { id: "TRO-A27", name: "TRO - A27", image: "/images/products/acrylic/TRO-A27.jpg", size: '10.75"x5.5" inch' },
    { id: "TRO-A28", name: "TRO - A28", image: "/images/products/acrylic/TRO-A28.jpg", size: '12" inch' },
    { id: "TRO-A29", name: "TRO - A29", image: "/images/products/acrylic/TRO-A29.jpg", size: '7.25"x6.75" inch' },
    { id: "TRO-A30", name: "TRO - A30", image: "/images/products/acrylic/TRO-A30.jpg", size: '9.5"x6.5" inch' },
    { id: "TRO-A31", name: "TRO - A31", image: "/images/products/acrylic/TRO-A31.jpg", size: '7"x7" inch' },
    { id: "TRO-A32", name: "TRO - A32", image: "/images/products/acrylic/TRO-A32.jpg", size: '7"x7" inch' },
    { id: "TRO-A33", name: "TRO - A33", image: "/images/products/acrylic/TRO-A33.jpg", size: '7"x5" inch' },
    { id: "TRO-A34", name: "TRO - A34", image: "/images/products/acrylic/TRO-A34.jpg", size: '7"x7" inch' },
    { id: "TRO-A35", name: "TRO - A35", image: "/images/products/acrylic/TRO-A35.jpg", size: '9"x5" inch' },
    { id: "TRO-A36", name: "TRO - A36", image: "/images/products/acrylic/TRO-A36.jpg", size: '9"x6" inch' },
    { id: "TRO-A37", name: "TRO - A37", image: "/images/products/acrylic/TRO-A37.jpg", size: '9"x4" inch' },
    { id: "TRO-A38", name: "TRO - A38", image: "/images/products/acrylic/TRO-A38.jpg", size: '10"x5" inch' },
    { id: "TRO-A39", name: "TRO - A39", image: "/images/products/acrylic/TRO-A39.jpg", size: '10"x5" inch' },
    { id: "TRO-A40", name: "TRO - A40", image: "/images/products/acrylic/TRO-A40.jpg", size: '10"x4" inch' },
    { id: "TRO-A41", name: "TRO - A41", image: "/images/products/acrylic/TRO-A41.jpg", size: '10"x4" inch' },
    { id: "TRO-A42", name: "TRO - A42", image: "/images/products/acrylic/TRO-A42.jpg", size: '8"x7" inch' },
    { id: "TRO-A43", name: "TRO - A43", image: "/images/products/acrylic/TRO-A43.jpg", size: '8"x6" inch' },
    { id: "TRO-A44", name: "TRO - A44", image: "/images/products/acrylic/TRO-A44.jpg", size: '9"x6" inch' },
    { id: "TRO-A45", name: "TRO - A45", image: "/images/products/acrylic/TRO-A45.jpg", size: '7"x3" inch' },
    { id: "TRO-A46", name: "TRO - A46", image: "/images/products/acrylic/TRO-A46.jpg", size: '8"x5" inch' },
    { id: "TRO-A47", name: "TRO - A47", image: "/images/products/acrylic/TRO-A47.jpg", size: '8"x6" inch' },
    { id: "TRO-A48", name: "TRO - A48", image: "/images/products/acrylic/TRO-A48.jpg", size: '10"x4" inch' },
    { id: "TRO-A49", name: "TRO - A49", image: "/images/products/acrylic/TRO-A49.jpg", size: '8"x5" inch' },
    { id: "TRO-A50", name: "TRO - A50", image: "/images/products/acrylic/TRO-A50.jpg", size: '9"x4" inch' },
    { id: "TRO-A51", name: "TRO - A51", image: "/images/products/acrylic/TRO-A51.jpg", size: '8"x6" inch' },
    { id: "TRO-A52", name: "TRO - A52", image: "/images/products/acrylic/TRO-A52.jpg", size: '9"x5" inch' },
    { id: "TRO-A53", name: "TRO - A53", image: "/images/products/acrylic/TRO-A53.jpg", size: '7"x7" inch' },
    { id: "TRO-A54", name: "TRO - A54", image: "/images/products/acrylic/TRO-A54.jpg", size: '7"x4" inch' },
    { id: "TRO-A55", name: "TRO - A55", image: "/images/products/acrylic/TRO-A55.jpg", size: '8"x5" inch' },
    { id: "TRO-A56", name: "TRO - A56", image: "/images/products/acrylic/TRO-A56.jpg", size: '10"x4" inch' },
    { id: "TRO-A57", name: "TRO - A57", image: "/images/products/acrylic/TRO-A57.jpg", size: '7"x6" inch' },
    { id: "TRO-A58", name: "TRO - A58", image: "/images/products/acrylic/TRO-A58.jpg", size: '9"x5" inch' },
    { id: "TRO-A59", name: "TRO - A59", image: "/images/products/acrylic/TRO-A59.jpg", size: '10"x3" inch' },
    { id: "TRO-A60", name: "TRO - A60", image: "/images/products/acrylic/TRO-A60.jpg", size: '10"x6" inch' },
    { id: "TRO-A61", name: "TRO - A61", image: "/images/products/acrylic/TRO-A61.jpg", size: '10"x5" inch' },
  ],
  "fiber-trophy": [
    { id: "TRO-F1", name: "TRO - F1", image: "/images/products/fiber/TRO-F1.jpg", size: 'A 10" B 8.5" C 7.5" inch' },
    { id: "TRO-F2", name: "TRO - F2", image: "/images/products/fiber/TRO-F2.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F3", name: "TRO - F3", image: "/images/products/fiber/TRO-F3.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F4", name: "TRO - F4", image: "/images/products/fiber/TRO-F4.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F5", name: "TRO - F5", image: "/images/products/fiber/TRO-F5.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F6", name: "TRO - F6", image: "/images/products/fiber/TRO-F6.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F7", name: "TRO - F7", image: "/images/products/fiber/TRO-F7.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F8", name: "TRO - F8", image: "/images/products/fiber/TRO-F8.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F9", name: "TRO - F9", image: "/images/products/fiber/TRO-F9.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F10", name: "TRO - F10", image: "/images/products/fiber/TRO-F10.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F11", name: "TRO - F11", image: "/images/products/fiber/TRO-F11.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F12", name: "TRO - F12", image: "/images/products/fiber/TRO-F12.jpg", size: 'A 10" B 9" C 8" inch' },
    { id: "TRO-F13", name: "TRO - F13", image: "/images/products/fiber/TRO-F13.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F14", name: "TRO - F14", image: "/images/products/fiber/TRO-F14.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F15", name: "TRO - F15", image: "/images/products/fiber/TRO-F15.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F16", name: "TRO - F16", image: "/images/products/fiber/TRO-F16.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F17", name: "TRO - F17", image: "/images/products/fiber/TRO-F17.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F18", name: "TRO - F18", image: "/images/products/fiber/TRO-F18.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F19", name: "TRO - F19", image: "/images/products/fiber/TRO-F19.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F20", name: "TRO - F20", image: "/images/products/fiber/TRO-F20.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F21", name: "TRO - F21", image: "/images/products/fiber/TRO-F21.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F22", name: "TRO - F22", image: "/images/products/fiber/TRO-F22.jpg", size: 'A 9.5" B 8.5" C 7.5" inch' },
    { id: "TRO-F23", name: "TRO - F23", image: "/images/products/fiber/TRO-F23.jpg", size: '9.5" inch' },
    { id: "TRO-F24", name: "TRO - F24", image: "/images/products/fiber/TRO-F24.jpg", size: '8.5" inch' },
    { id: "TRO-F25", name: "TRO - F25", image: "/images/products/fiber/TRO-F25.jpg", size: '8.5" inch' },
    { id: "TRO-F26", name: "TRO - F26", image: "/images/products/fiber/TRO-F26.jpg", size: '8.5" inch' },
    { id: "TRO-F27", name: "TRO - F27", image: "/images/products/fiber/TRO-F27.jpg", size: '8.5" inch' },
    { id: "TRO-F28", name: "TRO - F28", image: "/images/products/fiber/TRO-F28.jpg", size: '10" inch' },
    { id: "TRO-F29", name: "TRO - F29", image: "/images/products/fiber/TRO-F29.jpg", size: '8.5" inch' },
    { id: "TRO-F30", name: "TRO - F30", image: "/images/products/fiber/TRO-F30.jpg", size: '10" inch' },
    { id: "TRO-F31", name: "TRO - F31", image: "/images/products/fiber/TRO-F31.jpg", size: '8.5" inch' },
    { id: "TRO-F32", name: "TRO - F32", image: "/images/products/fiber/TRO-F32.jpg", size: '9.5" inch' },
  ],
  "metal-trophy": [],
  "sports-medals": [],
  "corporate-gifts": [],
};

export const CITIES = [
  { slug: "delhi", name: "Delhi" },
  { slug: "noida", name: "Noida" },
  { slug: "gurgaon", name: "Gurgaon" },
  { slug: "ghaziabad", name: "Ghaziabad" },
  { slug: "faridabad", name: "Faridabad" },
] as const;
